### PR TITLE
Coordinate for each school

### PR DESCRIPTION
**Pull request by Cng000**
Made a new json file containing the school's lat and long, and a script that will update the values after populated db is called.

### CODE REVIEW

**Comment by drsh0x** [comment]
Do you have a `.gitignore` file in your local repo? I noticed that `.venv`, migrations and *.pyc are being pushed to remote, can you fix that?

**Comment by Cng000** [comment]
Yes I do.
image

**Comment by drsh0x** [comment]
well, there is an issue with this commit dc45b7575aa882b7cf3fee1456e2c55bac654da0 
try reverting it or squashing your changes then reclone the repo, obviously merging this PR wouldn't be a good idea

**Comment by drsh0x** [comment]
It looks like you only need the management script + json. Would it be possible to combine all db logic into a single command that populates img urls and map coordinates?

**Comment by Cng000** [comment]
Yeah i can make into a single script that populate both image url and coor. Do later tho, need to work on the paper.

**Review by mousta0x — CHANGES_REQUESTED** [review]
see above

**Pull request closed without merging**
